# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0x90cdffff
maximizescreencolor = 0xb8c8d9ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd1bfe7ff
globalcolor = 0x004b72ff
overlaycolor = 0x394856ff
