# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0x7cd0ffff
maximizescreencolor = 0xb5c9d7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xcac1e9ff
globalcolor = 0x004c69ff
overlaycolor = 0x374955ff
