# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131313ff
bordercolor = 0x919191ff
focuscolor = 0xffb4a9ff
maximizescreencolor = 0xe7bdb7ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xdfc38cff
globalcolor = 0x7d2b22ff
overlaycolor = 0x5d3f3bff
