
exec-once=qs -c noctalia-shell
exec-once=kmonad ~/.config/kmonad/config.kbd
exec-once=wlr-randr --output eDP-1 --custom-mode 2560x1600@60
exec-once=easyeffects --gapplication-service

# for screen share
exec-once = "systemctl --user start xdg-desktop-portal.service --ignore-dependencies &"

exec-once=foot -a foot-boot
# exec-once=webcord
exec-once=helium-browser

#exec-once=zen-browser
# exec-once=com.discordapp.Discord
